# Config file for automatic testing at travis-ci.org

dist: bionic
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -U pip
    - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script:
    - tox


# Deploy to PyPI
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: BpZ6Rm15kXgaWd7nhNPqT2FiFQydoDjvpQFewHAJxIovw9yNGLBThpC8w7M/9rv/zrOZ3PquQVFwD90Bd1xzo5kvadiJUogi0cx7J2eqVBX1QqNJzMGbdaQ8klESlQca2G2o92h0Pu5ppo3WJfe5q342LZ/bkAR7T0NmQlUhnmnFfgCMTXg9kprKoINq6OJB2h1N/Wsjn2GRu9kmnTHf2XyOj9wpg+hRXmcaOgbS7kFjBhVEsC6BvcFD5TnroF4M3xeg0DXpwoCR2a/pDdkg61qg8p3MSsbiPqNoZS7Aq/BB16noa5I+OA9kqxB3JPMv2T8XQFz5Q+Peu0BVUrySl4/regvG728GGfFmcfNXvBdtWsYyXysQT/Knzlw1Ndw/bVPwFlf+iipMkxhKnkk1PjNFzTk39PUmZA5hHp6NcyZX0QG9bDNlPMGiYjDy29Wxvz3O2ren5dtTMKXYVhPaRPFAiCJSvT1PkFeqJpURiw6TWOtcZs/inVTuXLhQzbQhH8JaklW4n6LZA2G4yafj68Sx75yK3pZIF9XsQrt3iiClUfl2wtatEIt7duIEnukNHHSVt3mep0scOVZVTt3nfvctHA0goMv8t6QtJVIBraZlV42Us2GYY6xJYFXj4RHAe7u20iuNgjxJRloRymiCFqYlyR8hxKfoF0qFcpBKchw=
  distributions: "sdist bdist_wheel"
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
